version: "3.9"

networks:
  financas-app:
    driver: bridge

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_financasapp
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Coti@2025"      
    networks:
      - financas-app
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_financasapp
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - financas-app

volumes:
  sqlserver_data:
